### ISSUE TITLE
Question: Commands for the CDU buttons?

### ISSUE THREAD

**Issue by Altalus** [Luuk3333/FFA320Connector#1]
Looking at my options for building a cockpit based on the FF A320 and this plugin is a godsend, but I seem not to be able to find if I can bind the buttons of a physical CDU to the CDU in the airplane.

Any idea?

Thank you for saving this project 👍

**Comment by Luuk3333** [comment]
Hey!
The datarefs and commands for the FFA320 are defined in the config.cfg file. However not all buttons are currently defined. To add the items you'll need to define them in a custom.cfg file as noted in the [config.cfg](https://github.com/Luuk3333/FFA320Connector/blob/df3aca2da768ee242515450cb650006eedbccb29/bin/FFA320Connector/config.cfg#L65) file.

I created a custom.cfg file with the left MCDU (MCDU1) buttons and lights, but I haven't tested all items yet.
You can find the file [here](https://gist.githubusercontent.com/Luuk3333/9e1f9ea3261bc9d498e8e65cb93360ec/raw/e62c5250000c048a4e260e267561cacbebf1149c/custom.cfg). You can replace 'Luuk' with any name, that's just how the datarefs are named inside X-Plane. If I recall correctly, you should be able to define the right MCDU by copying all lines and renaming 'MCDU1' to 'MCDU2'.

**Comment by Altalus** [comment]
This file is awesome and will help a lot! 💯 

Thank you for your time and your help.
