### ISSUE TITLE
Commands Mis-spelt in Config.cfg

### ISSUE THREAD

**Issue by scotflieger** [Luuk3333/FFA320Connector#3]
There are several mis-spelling of Cycle in config.cfg. Change all "cylce" to "cycle" and "Cycle" to "Cycle". Beware of initial capitals.

**Comment by Sakarias-Longhorn** [comment]
I just opened a pull request for that.

**Comment by Luuk3333** [comment]
Resolved by merging pull request #6 in commit 580dc07dcbde9d0d9016fdb9c9fe5cd53f924b32. Thanks!
